# Habilitar comunicación por comandos (necesario para el script)
ipc = on

# Opcional: desactiva el texto de la parte inferior de la pantalla
splash = false

# Precargar la imagen en la memoria
preload = /home/pedro/Imágenes/wallpapers/grey_lain_wallpaper.jpg

# Aplicar el fondo de pantalla a todos los monitores
wallpaper = ,/home/pedro/Imágenes/wallpapers/grey_lain_wallpaper.jpg

wallpaper {
    monitor = HDMI-A-1
    path = /home/pedro/Imágenes/wallpapers/grey_lain_wallpaper.jpg
    fit_mode = cover
}
